version: '3.4'

services:
  e-commerceapp.api.webapi:
    image: ${DOCKER_REGISTRY-}ecommerceappapiwebapi
    build:
      context: .
      dockerfile: src/Api/WebApi/E-CommerceApp.Api.WebApi/Dockerfile

  ecommerce.projections.userservice:
    image: ${DOCKER_REGISTRY-}ecommerceprojectionsuserservice
    build:
      context: .
      dockerfile: src/Projections/ECommerce.Projections.UserService/Dockerfile

